/// Every app command registered in `generate_handler!` (src/lib.rs). Listing them here makes Tauri
/// generate `allow-<command>` / `deny-<command>` permissions (permissions/autogenerated) and,
/// once an app manifest exists, app commands are only callable from windows whose capability
/// grants them (capabilities/*.json). A command missing here is rejected at runtime, so keep this
/// list in sync (the `build_rs_lists_every_registered_command` test checks it).
const APP_COMMANDS: &[&str] = &[
    "toggle_quick_input",
    "hide_quick_input",
    "show_main_window",
    "submit_word",
    "enrich_word_with_gemini",
    "generate_grammar_exercises_ai",
    "generate_vocabulary_recommendations_ai",
    "get_clipboard_text",
    "check_cli_status",
    "send_desktop_notification",
    "trigger_review_navigation",
    "show_review_popup",
    "hide_review_popup",
    "show_review_nudge",
    "hide_review_nudge",
    "is_cursor_over_nudge",
    "take_review_nudge_payload",
    "prepare_update_exit",
    "cancel_update_exit",
    "get_popup_blockers",
    "log_debug",
    "set_tray_due_count",
    "export_backup",
    "grade_sentence_ai",
    "correct_writing_ai",
    "compute_fsrs_parameters",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
